#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit Relay
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitRelay/Base/Library')
import os
import json

import JackrabbitRelay as JRR

###
### Main code base. Place order on exchange
###

relay=JRR.JackrabbitRelay()
if relay.GetArgsLen() > 3:
    exchangeName=relay.GetExchange()
    account=relay.GetAccount()
    asset=relay.GetAsset()
else:
    print("An exchange, (sub)account, and an asset must be provided.")
    sys.exit(1)

markets=relay.GetMarkets()

last = None
while True:
    ticker = relay.GetTicker(symbol=asset)
    key = (ticker['Ask'], ticker['Bid'])

    if key != last:
        print(f"{ticker['DateTime']} {ticker['Ask']:.8f} {ticker['Spread']:.8f} {ticker['Bid']:.8f}")
        last = key

